-- DROP AND CREATE DATABASE
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'Bank_Core_API')
BEGIN
    ALTER DATABASE Bank_Core_API SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE Bank_Core_API;
END;
GO

CREATE DATABASE Bank_Core_API COLLATE SQL_Latin1_General_CP1_CS_AS;
GO

USE Bank_Core_API;
GO
